version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - kittygram_static:/backend_static/
      - media:/app/media/
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - kittygram_static:/static
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - kittygram_static:/static
      - media:/app/media/
